services:
  backend:
    build: 
      context: https://github.com/icaropk/yt.git#main:backend
    restart: always

  frontend:
    build:
      context: https://github.com/icaropk/yt.git#main:frontend
    ports:
      - "3000:80"
    restart: always
